spring:
  application:
    name: ditda-notification-worker
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  config:
    import: optional:file:.env[.properties]

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          multiplier: 2
          max-interval: 10s
          max-retries: 2
        default-requeue-rejected: false

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 10000
          writetimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

  endpoint:
    health:
      show-details: never

  otlp:
    metrics:
      export:
        enabled: false

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}

  tracing:
    sampling:
      probability: 1.0
    export:
      otlp:
        enabled: ${OTLP_TRACING_ENABLED}

  metrics:
    tags:
      application: ${spring.application.name}